# This is a basic workflow to help you get started with Actions

name: Test AWS s3 storage

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
            path: "requirements.txt"
      # Runs a single command using the runners shell
      - name: Test writing a table to AWS
        working-directory: ./src
        run: |
              python roles_proccess.py --run-type="write_data_test"
              
        env:
          aws_access: ${{ secrets.aws_access }}
          aws_key: ${{ secrets.aws_key }}
          
      - name: Test reading a table to AWS
        working-directory: ./src
        run: |
              python roles_proccess.py --test-name="load_data_test"
              
        env:
          aws_access: ${{ secrets.aws_access }}
          aws_key: ${{ secrets.aws_key }}
