# This is a basic workflow to test if the docker container can be built

name: run_container

on:
  #Run this workflow manually from the Actions tab
  workflow_dispatch:

# env:
#   IMAGE_NAME: load_role_table

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run image to proccess LOP Roles table
        run: |
              docker build . --file role_tbl_dockerfile --tag $proccess_roles --label "runnumber=${GITHUB_RUN_ID}"
              docker run proccess_roles --run-type="process" 
        env:
          aws_key: ${{ secrets.aws_key }}
          aws_access: ${{ secrets.aws_access }}
